DROP TABLE IF EXISTS Occupations;
DROP TABLE IF EXISTS Triangles;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Station;

DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS Lead_Manager;
DROP TABLE IF EXISTS Senior_Manager;
DROP TABLE IF EXISTS Manager;
DROP TABLE IF EXISTS Employee;

